name: Deploy IMAP Listener
on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        required: true
        type: string

jobs:
  diff_imap:
    uses: ./.github/workflows/diff-last-run.yml
    with:
      CHECK_DIFF_LOCATIONS: imap-listener/ docker/imap-listener/

  build_imap:
    runs-on: ubuntu-latest
    needs: diff_imap
    if: ${{ needs.diff_imap.outputs.changes == 'true' }}
    environment:
      name: ${{ inputs.ENVIRONMENT }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: "AWS: Install CLI"
        run: |
          curl --fail -s -S "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli --update

      - name: "AWS: Configure credentials"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Setup buildx
        uses: docker/setup-buildx-action@v3

      - name: Build IMAP listener image
        uses: docker/build-push-action@v6
        with:
          context: ./imap-listener
          file: ./docker/imap-listener/Dockerfile
          push: false
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            public.ecr.aws/n0p8j4k5/trassenscout/imap-listener:${{ github.sha }}
            public.ecr.aws/n0p8j4k5/trassenscout/imap-listener:${{ inputs.ENVIRONMENT }}-latest

      - name: Push IMAP listener image
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/n0p8j4k5/
          docker push --all-tags public.ecr.aws/n0p8j4k5/trassenscout/imap-listener
